=== devgateway/oc-explorer/persistence-mongodb/src/main/resources/release-package-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schema for an Open Contracting Release Package",
    "description": "Note that all releases within a release package must have a unique releaseID within this release package.",
    "type": "object",
    "required": ["uri", "publisher", "publishedDate", "releases"],
    "properties": {
        "uri": {
            "title": "Package Identifier",
            "description": "The URI of this package that identifies it uniquely in the world.",
            "type": "string",
            "format": "uri"
        },
        "publishedDate": {
            "description": "The date that this package was published. Ideally this should be the latest date that there is release information in this package.",
            "type": "string",
            "format": "date-time"
        },
        "releases": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "http://ocds.open-contracting.org/standard/r/1__0__0/release-schema.json" },
            "uniqueItems": true
        },
        "publisher": { 
            "description": "Information to uniquely identify the publisher of this package.",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "scheme": {
                    "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
                    "type": ["string", "null"],
                    "format": "uri"
                },
                "uid": {
                    "description": "The unique ID for this entity under the given ID scheme.",
                    "type": ["string", "null"]
                },
                "uri": {
                    "type": ["string", "null"],
                    "format" : "uri"
                }
            },
            "required": ["name"]
        },
        "license": {
            "description": "A link to the license that applies to the data in this datapackage. A Public Domain Dedication or [Open Definition Conformant](http://opendefinition.org/licenses/) license is strongly recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions. ",
            "type": ["string", "null"],
            "format": "uri"
        },
        "publicationPolicy": {
            "description": "A link to a document describing the publishers [publication policy](http://ocds.open-contracting.org/standard/r/1__0__0/en/implementation/publication_patterns/#publication-policy).",
            "type": ["string", "null"],
            "format": "uri"
        }
    }
}

=== devgateway/oc-explorer/persistence-mongodb/src/test/resources/json/release-excel-export.json
{
    "uri":"http://standard.open-contracting.org/examples/",
    "publishedDate":"2009-03-15T14:45:00Z",
    "publisher":{
        "scheme":"GB-COH",
        "uid":"09506232",
        "name":"Open Data Services Co-operative Limited",
        "uri":"http://standard.open-contracting.org/examples/"
    },
    "license":"http://opendatacommons.org/licenses/pddl/1.0/",
    "publicationPolicy":"https://github.com/open-contracting/sample-data/",
    "releases":[
        {
            "id":"12345",
            "ocid":"ocid-12345",
            "tag":[
                "award"
            ],
            "initiationType":"tender",
            "buyer":{
                "identifier":{
                    "scheme":"GB-LAC",
                    "id":"E09000003",
                    "legalName":"London Borough of Barnet",
                    "uri":"http://www.barnet.gov.uk/"
                },
                "name":"London Borough of Barnet",
                "address":{
                    "streetAddress":"4, North London Business Park, Oakleigh Rd S",
                    "locality":"London",
                    "region":"London",
                    "postalCode":"N11 1NP",
                    "countryName":"United Kingdom"
                },
                "contactPoint":{
                    "name":"Procurement Team",
                    "email":"procurement-team@example.com",
                    "telephone":"01234 345 346",
                    "faxNumber":"01234 345 345",
                    "url":"http://example.com/contact/"
                }
            },
            "awards":[
                {
                    "id":"ocds-213czf-000-00001-award-01",
                    "title":"Award of contract to build new cycle lanes in the centre of town.",
                    "description":"AnyCorp Ltd has been awarded the contract to build new cycle lanes in the centre of town.",
                    "status":"pending",
                    "date":"2010-05-10T09:30:00Z",
                    "value":{
                        "amount":11000000,
                        "currency":"GBP"
                    },
                    "suppliers":[
                        {
                            "identifier":{
                                "scheme":"GB-COH",
                                "id":"1234567844",
                                "legalName":"AnyCorp Ltd",
                                "uri":"http://www.anycorp.example"
                            },
                            "additionalIdentifiers":[
                                {
                                    "scheme":"GB-VAT",
                                    "id":"987654321"
                                }
                            ],
                            "name":"AnyCorp Cycle Provision",
                            "address":{
                                "streetAddress":"100 Anytown Lane",
                                "locality":"Anytown",
                                "region":"AnyCounty",
                                "postalCode":"AN1 1TN",
                                "countryName":"United Kingdom"
                            }
                        },
                        {
                            "identifier":{
                                "scheme":"GB-COH",
                                "id":"900102",
                                "legalName":"New Name Ltd",
                                "uri":"http://www.newname.org"
                            },
                            "name":"New Name 222",
                            "address":{
                                "streetAddress":"3003 Van Ness",
                                "locality":"Washington",
                                "region":"DC",
                                "postalCode":"20008",
                                "countryName":"United States"
                            }
                        }
                    ],
                    "items":[
                        {
                            "id":"0001",
                            "description":"string 1",
                            "classification":{
                                "scheme":"CPV",
                                "id":"45233130",
                                "description":"Construction work for highways",
                                "uri":"http://cpv.data.ac.uk/code-45233130"
                            },
                            "quantity":8,
                            "unit":{
                                "name":"Miles",
                                "value":{
                                    "amount":137000,
                                    "currency":"GBP"
                                }
                            }
                        },
                        {
                            "id":"0002",
                            "description":"string 2",
                            "classification":{
                                "scheme":"CPV",
                                "id":"200000",
                                "description":"Some description...",
                                "uri":"http://cpv.data.ac.uk/code-45233130"
                            },
                            "quantity":3,
                            "unit":{
                                "value":{
                                    "amount":137000000,
                                    "currency":"RON"
                                }
                            }
                        }
                    ]
                }
            ]
        },
        {
            "id":"678",
            "ocid":"ocid-678",
            "tag":[
                "award"
            ],
            "initiationType":"tender",
            "buyer":{
                "identifier":{
                    "scheme":"GB-LAC",
                    "id":"E09000003",
                    "legalName":"London Borough of Barnet",
                    "uri":"http://www.barnet.gov.uk/"
                },
                "name":"London Borough of Barnet",
                "address":{
                    "streetAddress":"4, North London Business Park, Oakleigh Rd S",
                    "locality":"London",
                    "region":"London",
                    "postalCode":"N11 1NP",
                    "countryName":"United Kingdom"
                },
                "contactPoint":{
                    "name":"Procurement Team",
                    "email":"procurement-team@example.com",
                    "telephone":"01234 345 346",
                    "faxNumber":"01234 345 345",
                    "url":"http://example.com/contact/"
                }
            },
            "awards":[
                {
                    "id":"ocds-213czf-000-00001-award-01",
                    "title":"Award of contract to build new cycle lanes in the centre of town.",
                    "description":"AnyCorp Ltd has been awarded the contract to build new cycle lanes in the centre of town.",
                    "status":"pending",
                    "date":"2010-05-10T09:30:00Z",
                    "value":{
                        "amount":11000000,
                        "currency":"GBP"
                    },
                    "suppliers":[
                        {
                            "identifier":{
                                "scheme":"GB-COH",
                                "id":"1234567844",
                                "legalName":"AnyCorp Ltd",
                                "uri":"http://www.anycorp.example"
                            },
                            "additionalIdentifiers":[
                                {
                                    "scheme":"GB-VAT",
                                    "id":"987654321"
                                }
                            ],
                            "name":"AnyCorp Cycle Provision",
                            "address":{
                                "streetAddress":"100 Anytown Lane",
                                "locality":"Anytown",
                                "region":"AnyCounty",
                                "postalCode":"AN1 1TN",
                                "countryName":"United Kingdom"
                            }
                        },
                        {
                            "identifier":{
                                "scheme":"GB-COH",
                                "id":"900102",
                                "legalName":"New Name Ltd",
                                "uri":"http://www.newname.org"
                            },
                            "name":"New Name 222",
                            "address":{
                                "streetAddress":"3003 Van Ness",
                                "locality":"Washington",
                                "region":"DC",
                                "postalCode":"20008",
                                "countryName":"United States"
                            }
                        }
                    ],
                    "items":[
                        {
                            "id":"0001",
                            "description":"string 1",
                            "classification":{
                                "scheme":"CPV",
                                "id":"45233130",
                                "description":"Construction work for highways",
                                "uri":"http://cpv.data.ac.uk/code-45233130"
                            },
                            "quantity":8,
                            "unit":{
                                "name":"Miles",
                                "value":{
                                    "amount":137000,
                                    "currency":"GBP"
                                }
                            }
